name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List files after checkout
        run: ls -la
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          echo "Contenu du package.json avant installation:"
          cat package.json || echo "package.json non trouvé"
          npm install
          echo "Dépendances installées:"
          ls -la node_modules || echo "Dossier node_modules non trouvé"
        
      - name: Build
        run: |
          echo "Exécution de la commande build"
          npm run build || echo "Erreur dans la commande de build"
          echo "Contenu après build:"
          ls -la
        
      - name: Check build output
        run: |
          echo "Vérification du dossier dist:"
          ls -la dist || echo "Dossier dist non trouvé"
          echo "Contenu de index.html (si existe):"
          cat dist/index.html || echo "index.html non trouvé dans dist"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Ajustez si nécessaire

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4